<?php
namespace modava\filemanager\components;

use backend\components\MyController;

class MyFilemanagerController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
